---

- name: Download neofs-storage binary
  ansible.builtin.get_url:
    url: "{{ neofs_storage__bin_url }}"
    dest: "{{ neofs_storage__bin_path }}"
    owner: 'root'
    group: 'root'
    mode: '0755'
  notify:
    - Restart neofs-storage service
