---

- name: Ensure there is node key
  ansible.builtin.copy:
    src: "{{ neofs_storage__key }}"
    dest: "{{ neofs_storage__key_path }}"
    owner: 'root'
    group: "{{ neofs_storage__group }}"
    mode: '0640'
    notify:
      - Restart neofs-storage service
